### PR TITLE
fix #31 and some deprecations

### LINKED ISSUE #31: UndefVarError: lasttag not defined
`julia> @iprofile f2(x) = 2*x
ERROR: UndefVarError: lasttag not defined`

```
julia> versioninfo()
Julia Version 0.5.0-dev+429
Commit f71e449 (2015-09-29 09:47 UTC)
Platform Info:
  System: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

### PR DESCRIPTION
**Pull request by JobJob**
Fixes https://github.com/timholy/IProfile.jl/issues/31 and a few deprecations on 0.4

### CODE REVIEW

File: src/IProfile.jl [hunk 1]
```diff
@@ -96,6 +96,7 @@ function insert_profile_block(fblock::Expr, tlast, tnow, timers, blast, bnow, by
     end
     descend = PROFILE_STATE & PROFILE_DESCEND > 0
     fblocknewargs = []
+    local lasttag
```
Comment (JobJob) [inline src/IProfile.jl]: Was curious how this ever worked, did scoping rules for for loops change? I would've thought `lasttag` would've been undefined on line 113 (now 114), since as I understand it `for` loops basically define a new scope at each iteration. The tests were failing before this change for me.

Comment (timholy) [inline src/IProfile.jl]: Yeah, I think IProfile was written in the julia 0.1 days or so. I seem to remember some julia commit---long ago---that changed this.

**Comment by timholy** [comment]
Thanks!

**Comment by timholy** [comment]
Should I tag a new release, or are you working on other changes?

**Comment by JobJob** [comment]
Yeah, tag it.

Started working on better support for nested functions but I don't think I'll finish it now.

Cheers.





From: Tim Holy

Sent: Saturday, 14 November 3:23 PM

Subject: Re: [IProfile.jl] fix #31 and some deprecations (#33)

To: timholy/IProfile.jl

Cc: Joel Mason



Should I tag a new release, or are you working on other changes?

File: src/IProfile.jl (hunk 1 above)
Comment (JobJob) [inline src/IProfile.jl]: :) nice
